In [2]:
import numpy as np 
import random 
import pandas as pd

In [4]:
rand_int = np.random.randint(0,100,1)


In [5]:
rand_int


array([45])

In [23]:
numbers = np.random.randint(1,101,100)


In [31]:
numbers

array([ 95,  27,  45,  70,  55, 100,   5,   2,  27,   9,  77,  69,  72,
        97,  49,  28,  21,  56,  77,  36,   7,  46,  22,  78,   6,  47,
        65,  97,   1,  61,  29,  75,  51,  89,  43,  81,  25,  34,  59,
         7,  97,  10,  84,  63,  28,  44,  36,  78,   8,  93,  18,  53,
        58,  47,  73,  75,  37,  13,   6,  75,  14,  82,  36,  81,  79,
        73,  47,  36,  96,   4,  49,  84,  51,  53,  30,  99,  84,  76,
        67,  92,  40,  69,  83,  64,  20,  80,  48,   5,  56,  85,  90,
        40,  60,  55,  63,  52,  33,  62,  30,  11])

In [54]:
numbers = np.random.randint(1,101,100).reshape(n,m)


In [67]:
table = pd.DataFrame(data = numbers,    
                        columns = ['N', 'M',]) 
conditions = [
    (table['N'] == 1 < numbers< 40 ) & (table['M'] == 1 < numbers < 50)]

table[column] == np.select(conditions)
    

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [57]:
table

N    M
0   22    3
1   55   48
2   60   47
3   80   74
4   31   82
5   86   49
6   54    2
7   78   88
8   15   80
9   22   85
10  33   77
11  65    7
12  21   25
13  69   55
14  77   50
15  42   69
16   3   65
17  33   97
18  34   12
19  97   20
20  26   65
21  24   17
22  84   97
23  12   36
24  53    8
25  80   10
26  21   99
27  75   31
28  35   96
29  13   87
30  56   85
31  84   97
32  33   53
33  33  100
34  93    6
35   5   60
36  15   72
37  85   97
38  69   36
39  55   43
40  74   44
41  19   98
42  21   20
43  41   71
44  49   88
45  46   66
46  52   11
47  78   26
48   2   80
49  88   44

In [93]:
third = table[:3]

In [94]:
third

N   M
0  22   3
1  55  48
2  60  47

In [124]:
def getTable(m, n):
    assert  (n > 0 and n <= 40) and (m > 0 and m <= 50)   
    numbers = np.random.randint(1,101,n*m).reshape(m, n)
    return numbers 

table = getTable(4,7)
 
    
    

    

In [125]:
table


array([[22, 35, 19, 55, 96, 50, 67],
       [11, 47, 17, 78, 44, 20, 44],
       [ 8, 31, 57, 45, 40, 58, 81],
       [12, 31, 97, 96, 79, 25, 64]])

In [107]:
table[2]

array([56, 70, 43, 49, 14, 81, 72])

In [109]:
for row in table:
    col = row[2]
    print(col)
    

13
25
43
63


In [111]:
[row[2] for row in table]

[13, 25, 43, 63]

In [126]:
[7 for num in table[-1]] 

[7, 7, 7, 7, 7, 7, 7]

In [128]:
table[-1] = [7 for num in table[-1]]  

In [127]:
table

array([[22, 35, 19, 55, 96, 50, 67],
       [11, 47, 17, 78, 44, 20, 44],
       [ 8, 31, 57, 45, 40, 58, 81],
       [12, 31, 97, 96, 79, 25, 64]])

In [129]:
table

array([[22, 35, 19, 55, 96, 50, 67],
       [11, 47, 17, 78, 44, 20, 44],
       [ 8, 31, 57, 45, 40, 58, 81],
       [ 7,  7,  7,  7,  7,  7,  7]])

In [137]:
last_col = []

for row in table:
    col_sum = row[0]+ row[1]
    last_col.append(col_sum)
    
print(last_col)
    
    
    
    
    

[57, 58, 39, 14]


for row in table:
    col = row[2]
    sum(col)
    